name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
      - name: Build
        run: hugo --minify
      - name: Define variables
        run: |
          echo "path_repo=$(pwd)" >> $GITHUB_ENV
          echo "path_export=public" >> $GITHUB_ENV
          echo "repo=$(echo $GITHUB_REPOSITORY | sed 's/.*\///')" >> $GITHUB_ENV
      - name: Check variables
        run: |
          echo "Github actor: ${GITHUB_ACTOR}"
          echo "Github repository: ${GITHUB_REPOSITORY}"
          echo "Path repo: ${path_repo}"
          echo "Path export: ${path_export}"
          echo "---------------------------------------------------------------------------------------------"
          echo "Folder contents at ${path_repo}:"
          ls -lh
          echo "---------------------------------------------------------------------------------------------"
          printenv
          sed --version

      - name: Pull repo, copy folder contents, push repo
        run: |
          # Add git info
          git config --global user.email "do_not_email@example.com"
          git config --global user.name "gh_action"

          # List folder contents
          echo "Folder contents at ${path_export}:"
          ls -lh ${path_export}

          # Clone gh-pages branch and remove old directories with same name
          git clone --single-branch --branch gh-pages "https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" tmprepo
          cd tmprepo
          git rm -r *
          git commit -m "Old directory deleted."

          cd ${path_repo}
          cp -r ${path_export}/* tmprepo/
          cd tmprepo
          echo "Folder contents at $(pwd):"
          ls -lh

          # Push changes back
          git add .
          git commit -m "Updated contents at $(date +%Y%m%d-%H%M%S)"
          git push origin
          
